### PR TITLE
Xperia ZL

### PR DESCRIPTION
**Pull request by ghost**
flashled_calc_parameters.cfg and kernel should be replaced to get this thing running on the Xperia ZL

Can I upload the vendor/blobs to github?

### CODE REVIEW

**Comment by jredestig** [comment]
Thanks. We have a device-sony-c6503 git prepared with the configuration needed for Xperia XL. The blobs on http://developer.sonymobile.com/ needs to be updated and the people who can do that is currently on vacation.

**Comment by ghost** [comment]
Can you upload the repo that is ready?
If you can't do it release it to all then : mithuncursed4eva@gmail.com

**Comment by sonyxperiadev** [comment]
https://github.com/sonyxperiadev/device-sony-c6503/ is now public. it does not build yet though.

**Comment by ghost** [comment]
Thanks

**Pull request closed without merging**
